version: '3.3'
services:
  
  mysql:
    image: mysql:8
    command: --sql-mode="NO_ENGINE_SUBSTITUTION" --character-set-server="utf8mb4" --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      ENV MYSQL_DATABASE: usuario
      TZ: America/Sao_Paulo
